### ISSUE TITLE
Support memcached with authorization

### ISSUE THREAD

**Issue by Mr-LiuDC** [sixhours-team/memcached-spring-boot#126]
If the memcached service requires user name and password authentication, how should I configure it?

**Comment by igorbolic** [comment]
Currently there is not such option. We will look into adding authentication support in the case you need it for your setup. Could you let us know if you use your own **memcached** service instance, or the one provided by cloud provider.

**Comment by Mr-LiuDC** [comment]
As I know, this docker image can run an authenticated memcached instancehttps://hub.docker.com/r/bitnami/memcached

**Comment by dondragon2** [comment]
Will there be a release to add authentication support? I want to connect to a redis server that requires a password

**Comment by igorbolic** [comment]
> Will there be a release to add authentication support? I want to connect to a redis server that requires a password

I'm not sure how it's related to the Redis, since this library is a wrapper for the Memcached cache. 

Anyway, we are planing to release the authentication support in a manner of week(s), depending what would be included within the next library release.

**Comment by igorbolic** [comment]
Supported with release version **2.5.0**
