### ISSUE TITLE
30 Days Expiration Limit

### ISSUE THREAD

**Issue by genericusername39** [sixhours-team/memcached-spring-boot#137]
Hi guys. Could you please allow the expiration to be limitless for different caches. Currently there is this hardcoded 30 days check. Is there a way to bypass this limitation?

**Comment by igorbolic** [comment]
This will be included with the next release.

**Comment by genericusername39** [comment]
Great, thanks

**Comment by igorbolic** [comment]
I've checked the existing code and it is already possible to configure the non-expiring cache. It is sufficient to set the expiration as `0` (zero) e.g.

```yaml
memcached.cache:
  expiration: 1d
  expiration-per-cache:
    books: 0
```

In the given example, your default expiration would be **1 day,** except for `books` cache being **limitless** i.e. the `books` cache will **never expire**.

Could you try it and let me know if this works for you?

**Comment by genericusername39** [comment]
Hi. Sorry for the late response. Unfortunately this does not fix my problem because I need a specific expiration of e.g. 90 days. A non-expiring cache is not applicable in my case
