### ISSUE TITLE
 Failed to process import candidates for configuration class [io.sixhours.memcached.cache.MemcachedCacheAutoConfiguration]; nested exception is java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy

### ISSUE THREAD

**Issue by mandaltu123** [sixhours-team/memcached-spring-boot#140]
Hi 

I am trying to use 'io.sixhours', name: 'memcached-spring-boot-starter', version: '2.4.2'.
However when I run this through docker, getting bellow mentioned issue. Kindly let me know a quick fix here.
https://stackoverflow.com/questions/71533729/docker-image-build-failure/71533804#71533804

**Comment by igorbolic** [comment]
@mandaltu123 
I was able to reproduce the issue using the `build.grade`example you've provided on [StackOverflow](https://stackoverflow.com/questions/71533729/docker-image-build-failure/71533804#71533804) and running a simple demo app with `./gradlew bootRun` (**Gradle 7.4**):

- On **Java 8** application startup fails with the following [error](https://github.com/sixhours-team/memcached-spring-boot/files/8323725/error.log) 👎 
- Running the application on **Java 11** or **Java 17** seem to resolve the application startup issue 👍 
- When using Spring Boot **2.1.x** on **Java 8** the application startup is successful as well 👍 

Therefore, the error you have reported seems to be related to the spring framework version (used by **Spring Boot 2.5.4**) where the `org.springframework.context.annotation.Import` annotation processing fails the when application is run on **Java 8**. 

There not a lot we can do for the memcached library to remedy the issue you've reported.
You might consider reporting the error on the [Spring Framework GitHub Issues](https://github.com/spring-projects/spring-framework/issues) or upgrade your environment to **Java 11** or even better to the latest **Java 17** (LTS version).
