### ISSUE TITLE
Measure cache hits and misses ratios

### ISSUE THREAD

**Issue by isaranchuk** [sixhours-team/memcached-spring-boot#37]
Add implementation of `CacheStatisticsProvider` to instrument cache hits and misses.
It will require changes to `MemcachedCache` to count cache hits and misses, so this information can be exposed via `/metrics` endpoint.

**Comment by igorbolic** [comment]
This would be a nice feature to have, and we are planing to add the full cache metrics in the foreseeable future. 
Rudimentary, cache metrics for hits & misses (per Spring Boot instance), could be easily added to the `MemcachedCache`, and probably shipped with the next release.
