### ISSUE TITLE
Custom Expiration for different objects

### ISSUE THREAD

**Issue by marwenhammami** [sixhours-team/memcached-spring-boot#40]
Sometimes or most of the times, setting a global expiration cache is not required, it would be very nice to have the option to set different expiration times for different cache names.
example : 
```
CacheConfiguration cacheConfiguration = new CacheConfiguration();
cacheConfiguration.put("name1", Expiration.byDeltaSeconds(86400));
cacheConfiguration.put("name2", Expiration.byDeltaSeconds(600));
```

**Comment by sasabolic** [comment]
Thanks @marwenhammami. We are working on this feature. 
It should be available soon.

**Comment by marwenhammami** [comment]
Thank you :D
