### ISSUE TITLE
Expirations Configuration

### ISSUE THREAD

**Issue by darius1907** [sixhours-team/memcached-spring-boot#49]
Hi, i think that Expiration configurations should be simply if you separate default expiration from cache expirations using a config like this:

```
# private Integer expiration = Default.EXPIRATION;
# setter already exist but deprecated
memcached.cache.expiration=10

#    private Map<String, Integer> expirations;
#    public void setExpirations(Map<String, Integer> expirations) {
#       this.expirations = expirations;
#    }
memcached.cache.expirations.cache1=10
memcached.cache.expirations.cache2=20
memcached.cache.expirations.cache3=30

```
instead of:
memcached.cache.expirations=600,cache1:20,cache2:15,cache3:30

i have expirienced that if i wrongly add a space in this string all configuration properties are ignored and fall to default value (indeed i have this evidence when cache address fall to localhost)

**Comment by sasabolic** [comment]
Agree, that would make configuration more readable than it is now.
We'll add support for this soon.
