### ISSUE TITLE
OperationTimeout Config

### ISSUE THREAD

**Issue by darius1907** [sixhours-team/memcached-spring-boot#50]
In my expirience working with cache I think that should be very useful have the chance to configure operationTimout in ConnectionFactoryBuilder (actually 2500 ms timeout should not be changed)

Any time an operation put/get is done  for every access to cache (namespace and key) a timeout of 2,5*n become a time very very huge.

**Comment by igorbolic** [comment]
Thank you for feedback. I'll try to add it (probably this week) as additional configuration option.

**Comment by mschaidinger** [comment]
You seem to have added this feature already, but it's not released so far. Any chance you might do that soon?

**Comment by igorbolic** [comment]
It will be released in the next few days.

**Comment by igorbolic** [comment]
@mschaidinger It has been released with version **1.3.2**

**Comment by mschaidinger** [comment]
Many thanks @igorbolic !
