### ISSUE TITLE
Caching not working properly when upgraded with new version 1.3.1. 

### ISSUE THREAD

**Issue by sonal020289** [sixhours-team/memcached-spring-boot#53]
I was work on the spring boot application. It was worked as expected when my version was 1.1.0. 
whenever I had been upgraded with the latest, it stops working. Will you please help me find out the cause.
I mean we need to follow any particular rule in our code structure? or I have to do some other things.
Please help me when you feel free. Thank you in advance.

**Comment by igorbolic** [comment]
Could you specify the Spring Boot version you are using, so that we could try to reproduce the issue.

**Comment by sonal020289** [comment]
@igorbolic thank you for your input. But it was code issue, in one class forgot to add the serialization with serialVersionUID. but now it is working propertly.
Thank you once again. :-)

**Comment by igorbolic** [comment]
No problem. Glad everything is working fine 👍  Closing the issue
