### ISSUE TITLE
Upgrade to spring-boot 2.2

### ISSUE THREAD

**Issue by davidkarlsen** [sixhours-team/memcached-spring-boot#55]
It would be nice to upgrade to spring-boot 2.2.x - or even 2.1.x (as we have to wait a bit before a 2.2-compatible spring-cloud is out).

Note that this means doing some stuff on the metrics side to adapt to the approach of using micrometer for stats.

I could do a PR if you can merge and publish a release?

I'd also like feedback on https://github.com/spring-projects/spring-boot/issues/18813 before I start this to avoid double-work.

**Comment by igorbolic** [comment]
Hi @davidkarlsen. This is something we have planned to work on, but just haven't got time to commence work on it. Currently they are some basic metrics support, but it was before micrometer was introduced with Spring Boot. Please do go ahead with the PR 👍 after the feedback from Pivotal team. Spring Boot **2.1.x** might be a better option, until Spring Cloud Hoxton is released

**Comment by davidkarlsen** [comment]
OK - it was turned down by SB team - so I guess we do the brush here. I'll get back with a WIP PR.

**Comment by davidkarlsen** [comment]
Fixed with #56 #61 #60 #59 #58

**Comment by davidkarlsen** [comment]
See https://github.com/spring-cloud/spring-cloud-release/issues/178#issuecomment-558819274 for the last missing piece (Hoxton pom).
